backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Product Name", name: "title", widget: "string", hint: "Enter the name of the product (e.g., Women's Silk Dress)" }
      - { label: "Price", name: "price", widget: "number", value_type: "float", hint: "Enter the price in dollars (e.g., 299.00)" }
      - { label: "Product Image", name: "image", widget: "image", hint: "Upload a clear image of the product" }
      - { label: "Category", name: "category", widget: "select", options: ["Men", "Women", "Accessories"], hint: "Choose the product category" }
      - { label: "Feature on Homepage", name: "featured", widget: "boolean", default: false, hint: "Check to highlight this product in the gallery" }